[workspace]
members = ["stcm2", "translate", "blume"]
resolver = "2"

[workspace.dependencies]
anyhow = "1"
encoding_rs = "0.8"
byteorder = "1.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
pyo3 = { version = "0.20", features = ["auto-initialize"] }
futures = "0.3"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.35", features = ["macros"] }
once_cell = "1.19"
rusqlite = { version = "0.30", features = ["bundled", "blob"] }
clap = { version = "4.4", features = ["derive"] }
ctrlc = { version = "3.4", features = ["termination"] }
