[package]
name = "blume"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
encoding_rs = "0.8"
byteorder = "1.5"
serde_json = "1"
pyo3 = { version = "0.20", features = ["auto-initialize"] }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.35", features = ["macros"] }
once_cell = "1.19"
rusqlite = { version = "0.30", features = ["bundled", "blob"] }
clap = { version = "4.4", features = ["derive"] }
